-- @block Lav tabel til mærker
CREATE TABLE brands (
    id SERIAL PRIMARY KEY,
    name TEXT
);

-- @block Indsæt mærker
INSERT INTO brands VALUES
(1, 'Nike'),
(2, 'Adidas'),
(3, 'Puma'),
(4, 'Under Armour'),
(5, 'Reebok'),
(6, 'Champion'),
(7, 'Levi''s'),
(8, 'Wrangler'),
(9, 'Tommy Hilfiger'),
(10, 'Calvin Klein'),
(11, 'Zara'),
(12, 'H&M'),
(13, 'Mango'),
(14, 'Uniqlo'),
(15, 'Bershka'),
(16, 'Pull & Bear'),
(17, 'Massimo Dutti'),
(18, 'COS'),
(19, '& Other Stories'),
(20, 'Topshop'),
(21, 'Gucci'),
(22, 'Louis Vuitton'),
(23, 'Prada'),
(24, 'Balenciaga'),
(25, 'Versace'),
(26, 'Saint Laurent'),
(27, 'Dior'),
(28, 'Burberry'),
(29, 'Fendi'),
(30, 'Alexander McQueen'),
(31, 'Supreme'),
(32, 'Off-White'),
(33, 'Stüssy'),
(34, 'A Bathing Ape (BAPE)'),
(35, 'Palace'),
(36, 'Carhartt WIP'),
(37, 'Fear of God'),
(38, 'Heron Preston'),
(39, 'KITH'),
(40, 'Rhude'),
(41, 'The North Face'),
(42, 'Patagonia'),
(43, 'Columbia'),
(44, 'Arc''teryx'),
(45, 'Salomon'),
(46, 'New Balance'),
(47, 'Asics'),
(48, 'Helly Hansen'),
(49, 'Moncler'),
(50, 'Stone Island');